### ISSUE TITLE
Update to using the version 2.17.1 of log4j

### ISSUE THREAD

**Issue by SultanSGillani** [fortify-ps/fortify-client-api#18]
Hello,

It looks like there is already a pull request for this change: https://github.com/fortify-ps/fortify-client-api/pull/17

However, 

The 6.1.2 Release of the Fortify API client leverages log4j 2.16.0. The latest version being recommended in Maven is 2.17.1, which was released on Dec. 27 to mitigate all variations of the log4j vulnerability. It looks like the community supporting this API client needs to make a change to leverage the new 2.17.1 log4j instead of 2.16.0.

Please advise when this is going to be merged. I find it ironic that this has not been fixed, as this is a security fix that is not implemented yet for a security client api.

Thanks,
Sultan

**Comment by rsenden** [comment]
PR #17 was not accepted as it was for upgrading log4j to 2.17.0 whereas there was already a new log4j version 2.17.1. Given the scrutiny that log4j is currently under, it was (and still is) very well possible that additional vulnerabilities would be identified, resulting in additional patch releases.

Since the vulnerabilities fixed by log4j 2.17.0 and 2.17.1 don't seem to have any security impact on the Fortify-provided integration utilities that utilize `fortify-client-api`, I chose to wait to see whether there would be any further log4j patches.

Anyway I have now done another round of updating all dependencies to the latest patch versions, this includes log4j 2.17.1. A new release of `fortify-client-api` should be available soon once all systems have processed the update.
